### ISSUE TITLE
db.Model.get_or_404()

### ISSUE THREAD

**Issue by danieldiekmeier** [coleifer/flask-peewee#162]
Hey,

I use this snippet in my projects all the time:

```
class RootModel(db.Model):
    @classmethod
    def get_or_404(cls, *args, **kwargs):
        try:
            return super(db.Model, cls).get(*args, **kwargs)
        except peewee.DoesNotExist:
            abort(404)
```

I just let every model inherit from this, instead of directly inheriting from `db.Model`, but maybe this would be a nice addition to flask-peewee?

<3

**Comment by coleifer** [comment]
I think I'm going to pass, since there is already a `get_object_or_404` method. Thanks, though!
