### ISSUE TITLE
Which alternative to use for building a REST API for Peewee?

### ISSUE THREAD

**Issue by kramer65** [coleifer/flask-peewee#163]
In the readme it says that flask-peewee is maintanance only, after which a couple suggestions are given for admin and authentication needs. 

I find myself wanting to build an elegant REST API for peewee though, for which no alternative suggestions age given. Any suggestions for a good alternative package to build a nice rest api for peewee with Flask would be very welcome!

**Comment by Ben-Baert** [comment]
You can still use Peewee and Flask together. See: http://docs.peewee-orm.com/en/latest/peewee/database.html#adding-request-hooks Using these request hooks will make sure you manage database connections correctly. There's little more to it. To add API functionality, you can do this manually or look at http://flask-restful-cn.readthedocs.io/en/0.3.4/.

For a Rest API, however, I'd look into Falcon. It seems quite a bit faster than Flask.

**Comment by coleifer** [comment]
For a REST API there's no reason you can't use flask-peewee if it suits your needs. I'm just not adding new features to it. It's not going away, I'm just no longer doing feature development for it.

Peewee also has a helper module for flask, in the `playhouse` extension library:

http://docs.peewee-orm.com/en/latest/peewee/playhouse.html#flask-utils

Hope that helps.
