### ISSUE TITLE
Peewee select().where() show empty result !

### ISSUE THREAD

**Issue by MahbubAlom** [coleifer/flask-peewee#167]
from app import *

query = Advertisement().select().where(Advertisement().clicks < 100)
for query in query:
	print(query.title)

i wanna to get all query which Advertisement().clicks < 100 .when i will run my program i saw its empty.result is None.why it will show me empty result.(my database store many clicks < 100).but it nothing show to me.why? any body help me please.how can i fix it? and how can i solve it ?

**Comment by coleifer** [comment]
.where(Advertisement.clicks < 100) (no parens)

This type of question belongs on stackoverflow. Don't post shit like that here again, thnx.
