### ISSUE TITLE
REST Filter by Boolean does not work

### ISSUE THREAD

**Issue by seanroark** [coleifer/flask-peewee#170]
SqlLite database. 

Flask-peewee 0.6.7 (latest in pypy)

```

class MyModel(Model):
    is_active = BooleanField(default=True)
```

api/mymodel/?is_active=False 

(or True) returns all row. 

api/mymodel/?is_active= 

Returns zero rows. Is it comparing the Boolean field to a string version of the get parameter? 

Like is_active='False'?

**Comment by coleifer** [comment]
Pushed a fix. Behavior in the version you're running is: 'anything' -> True, '' (empty string) -> False.

Change I pushed implements some argument cleaning, turning True/False/None (strings) into their Python equivalents.
