### ISSUE TITLE
Project license?

### ISSUE THREAD

**Issue by antlarr-suse** [coleifer/flask-peewee#172]
The setup.py file and pypi site identify flask-peewee as being licensed under the BSD license but the LICENSE file has the contents of the MIT license instead. Which one is the right project license?

Also, in case it's BSD, there are several flavours of the BSD license (check [the spdx.org site](https://spdx.org/licenses/)) with the most used ones being BSD-2-Clause and BSD-3-Clause. Which one would it be?

**Comment by coleifer** [comment]
MIT, sorry for the confusion!

**Comment by antlarr-suse** [comment]
Thanks for the quick fix!
