### ISSUE TITLE
api bad request

### ISSUE THREAD

**Issue by TechComet** [coleifer/flask-peewee#177]
Hi,

I try this example
http://docs.peewee-orm.com/projects/flask-peewee/en/latest/getting-started.html

```
curl -u admin:admin -d data='{"message": "hello api"}' http://127.0.0.1:5000/api/note/
curl: (3) [globbing] unmatched close brace/bracket in column 10
Bad request
```

**Comment by coleifer** [comment]
I don't know, something weird in your shell maybe?

**Comment by TechComet** [comment]
sorry .. It's error from curl on Windows
It's work on Linux
