### ISSUE TITLE
"maximum recursion depth exceeded" occurred in admin when deleting

### ISSUE THREAD

**Issue by wong2** [coleifer/flask-peewee#31]
As I said in issue #29,  I saw this error when I open the model with  a self-reference, and it was fixed.  
However, when I try to delete a model instance which has a foreign key point to that self-reference model in admin, this error occurred again.

**Comment by nad2000** [comment]
I ran into a similar issue with REST. I have cyclic foreign keys between Org and User and requesting eg **/api/user/1** resulted in "RecursionError: maximum recursion depth exceeded".  Perhaps it would be a good idea to specify, just as it is done with **model_to_dict**, recurse=True/False or depth=N with api.register or RestResource which would control how deep if any get_dictionary_from_object show should traverse? Cheers!
