### ISSUE TITLE
Admin treats a field with "choices" and "null" as mandatory

### ISSUE THREAD

**Issue by leaanthony** [coleifer/flask-peewee#79]
With the following class:

```
class Test(db.Model):
    end_time = CharField(choices=[(1,"one"), (2,"two")], null=True, default=None)
```

...the admin panel will not allow you to create a new record without selecting an option.

**Comment by den4uk** [comment]
I would like to re-open this ticket.

What was missed in the original discussion, that the intended field type used is a `CharField`, and the example uses `IntegerField`. The combination of `null` and `choices` works with the `IntegerField`, however, it makes the field as *required* when the field used is a `CharField`.
