### ISSUE TITLE
override default login template and admin login url

### ISSUE THREAD

**Issue by beebek** [coleifer/flask-peewee#91]
Is there a way to override the default login template ? I dont want to monkey patch the code. Also the admin url is 
http://127.0.0.1:5000/accounts/login/?next=%2Fadmin%2F

can it be made more simpler....

**Comment by thepythonist99** [comment]
Hi all,
I am so happy using flask-peewee. However, when I try to override the default login template, I'm unable to view the admin site. Also, the Auth.get_logged_in_user() always return **None** although I use the Auth to class to authenticate my users. 
What could be the problem ?

**Comment by coleifer** [comment]
You can try using the interactive debugger to see what's going on. https://docs.python.org/2/library/pdb.html

Without seeing your template it's awfully hard to know what the problem might be.

**Comment by thepythonist99** [comment]
Hi Charles,
Thanks for your quick reply. Here you have the log in view and it's template after I overrode :  

- **Login view** :  
`@app.route('/login/', methods=['GET', 'POST'])
def login():
    next_url = request.args.get('next')
    if request.method == 'POST':
        user = User.select().where(User.email == request.form['logdetail'])
        if user:
            try:
                session['logged_in'] = True
                session.permanent = True
                flash('You are now logged in', 'success')
                return redirect(next_url)
            except User.DoesNotExist:
                flash('Incorrect login details', 'info')
        else:
            flash('Incorrect email or password', 'info')

    return render_template('auth/login.html', next=next_url)`

- **Log in template** :  
`{% block content %}
    <div class="alert alert-secondary">
        <h6>
            Please Sign In to proceed
        </h6>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-6 col-sm-offset-6">
                 <div class="alert alert-secondary">
                      <form action="{{ url_for('login') }}" method="post">

                          <div class="form-group">
                                <label for="email" class="col-form-label">Email or Username</label>
                                <input type="text" class="form-control" id="email"
                                        name="logdetail" placeholder="Email or Username" required>
                          </div>

                          <div class="form-group">
                                <label for="password" class="col-form-label">Password</label>
                                <input type="password" class="form-control" id="password"
                                        name="logpassword" placeholder="Password" required>
                          </div>
                          <p>
                              <button class="btn btn-secondary">Login</button>
                              <a class="btn btn-link" href="{{ url_for('home') }}">Cancel</a>
                          </p>
                          <p class="small">
                              Don't have an account yet ?
                              <a href="{{ url_for('register') }}?next={{ url_for('home') }}" class="btn btn-link">
                                  Register
                              </a>
                          </p>
                      </form>
                 </div>
            </div>
        </div>
    </div>`

**Comment by coleifer** [comment]
Thanks!

So you'll want to store in the session a field named "user_pk" which is the primary key of the user model. In the `get_logged_in_user()` method of the `Auth` object, there is the following code:

```python
    def get_logged_in_user(self):
        if session.get('logged_in'):
            if getattr(g, 'user', None):
                return g.user

            try:
                return self.User.select().where(
                    self.User.active==True,
                    self.User.id==session.get('user_pk')
                ).get()
            except self.User.DoesNotExist:
                pass
```

My guess is that since you are not setting the `user_pk` field, the lookup fails.

I'd recommend, instead of doing the above (a standalone login view and manually hacking the session), subclassing the flask_peewee.auth.Auth class and overriding the appropriate methods. It'll result in more code, but it'll also be more semantically correct. Probably you'll want to override the `get_login_form()` method, the `login()` method, and possibly the `authenticate()` and `get_logged_in_user()` methods -- depending on how much customization you require.

If you need specific help beyond this, you should probably turn to stackoverflow for help.

**Comment by thepythonist99** [comment]
Thanks a lot Charles. I actually thought of overriding all those methods but I really needed your advise first before jumping in it. I'll do as you recommend and when am "successfully" done, I'll send a feedback. Just hoping the admin site problem will be fixed.
Thanks again !

**Comment by thepythonist99** [comment]
Hi Charles,
It worked !!! 
However the `BaseUser.check_password()` method in `authenticate()` on the **user instance** was raising this exception : `Can't convert NoneType into 'str' implicitly`. But when I removed that check, it worked. I would really love checking passwords.
Also, assuming my admin prefix is `/dashboard/`, I would like to know if it is possible to directly insert this in the url search bar and access the admin site without having to login on my site first before inserting the prefix in the search bar.
Those are the two main problems I am facing now but the essential is done and I quite happy with that.
Regards,
Patrick Silab.
