### ISSUE TITLE
Debug toolbar panel

### ISSUE THREAD

**Issue by imbolc** [coleifer/flask-peewee#94]
It would be nice to have it :)

**Comment by kevinisaac** [comment]
@coleifer I think what @imbolc meant is to have a panel for peewee in the Flask-DebugToolbar extension - [flask-debugtoolbar #56](https://github.com/mgood/flask-debugtoolbar/issues/56).

**Comment by klen** [comment]
I've added the Peewee support to Flask-DebugToolbar in my https://github.com/klen/flask-pw package.

**Comment by coleifer** [comment]
Awesome work @klen

**Comment by klen** [comment]
@coleifer Thank you!
